// Copyright (c) 2026.

#pragma once

#include <pybind11/pybind11.h>
#include <torch/extension.h>

namespace asym_gemm::qwen3_moe {

pybind11::tuple qwen3_gate_up_recompute_bwd_sm100_bf16_windowed(
    const torch::Tensor& x_sel,
    const torch::Tensor& dact_sel,
    const torch::Tensor& gate_low_rank_sel,
    const torch::Tensor& up_low_rank_sel,
    const torch::Tensor& gate_lora_B,
    const torch::Tensor& up_lora_B,
    const torch::Tensor& gate_up_weight_cpu,
    const torch::Tensor& selected_offsets,
    const torch::Tensor& selected_experts,
    int64_t p,
    int64_t q,
    int64_t bm,
    int64_t bk,
    int64_t g_work,
    double lora_scale,
    const std::string& mode,
    bool return_stats,
    const torch::Tensor& dS_down_sel,
    const torch::Tensor& down_mask_packed,
    double down_dropout_p);

static void register_apis(pybind11::module_& m) {
    namespace py = pybind11;
    m.def(
        "qwen3_gate_up_recompute_bwd_sm100_bf16_windowed",
        [](const torch::Tensor& x_sel,
           const torch::Tensor& dact_sel,
           const torch::Tensor& gate_low_rank_sel,
           const torch::Tensor& up_low_rank_sel,
           const torch::Tensor& gate_lora_B,
           const torch::Tensor& up_lora_B,
           const torch::Tensor& gate_up_weight_cpu,
           const torch::Tensor& selected_offsets,
           const torch::Tensor& selected_experts,
           int64_t p,
           int64_t q,
           int64_t bm,
           int64_t bk,
           int64_t g_work,
           double lora_scale,
           const std::string& mode,
           bool return_stats) {
            return qwen3_gate_up_recompute_bwd_sm100_bf16_windowed(
                x_sel,
                dact_sel,
                gate_low_rank_sel,
                up_low_rank_sel,
                gate_lora_B,
                up_lora_B,
                gate_up_weight_cpu,
                selected_offsets,
                selected_experts,
                p,
                q,
                bm,
                bk,
                g_work,
                lora_scale,
                mode,
                return_stats,
                torch::Tensor(),
                torch::Tensor(),
                0.0);
        },
        py::arg("x_sel"),
        py::arg("dact_sel"),
        py::arg("gate_low_rank_sel"),
        py::arg("up_low_rank_sel"),
        py::arg("gate_lora_B"),
        py::arg("up_lora_B"),
        py::arg("gate_up_weight_cpu"),
        py::arg("selected_offsets"),
        py::arg("selected_experts"),
        py::arg("p") = 32,
        py::arg("q") = 8,
        py::arg("bm") = 64,
        py::arg("bk") = 512,
        py::arg("g_work") = 128,
        py::arg("lora_scale") = 1.0,
        py::arg("mode") = "cache_first_window",
        py::arg("return_stats") = true);
    m.def(
        "qwen3_gate_up_recompute_bwd_sm100_bf16_windowed",
        [](const torch::Tensor& x_sel,
           const torch::Tensor& dact_sel,
           const torch::Tensor& gate_low_rank_sel,
           const torch::Tensor& up_low_rank_sel,
           const torch::Tensor& gate_lora_B,
           const torch::Tensor& up_lora_B,
           const torch::Tensor& gate_up_weight_cpu,
           const torch::Tensor& selected_offsets,
           const torch::Tensor& selected_experts,
           const torch::Tensor& dS_down_sel,
           const torch::Tensor& down_mask_packed,
           double down_dropout_p,
           int64_t p,
           int64_t q,
           int64_t bm,
           int64_t bk,
           int64_t g_work,
           double lora_scale,
           const std::string& mode,
           bool return_stats) {
            return qwen3_gate_up_recompute_bwd_sm100_bf16_windowed(
                x_sel,
                dact_sel,
                gate_low_rank_sel,
                up_low_rank_sel,
                gate_lora_B,
                up_lora_B,
                gate_up_weight_cpu,
                selected_offsets,
                selected_experts,
                p,
                q,
                bm,
                bk,
                g_work,
                lora_scale,
                mode,
                return_stats,
                dS_down_sel,
                down_mask_packed,
                down_dropout_p);
        },
        py::arg("x_sel"),
        py::arg("dact_sel"),
        py::arg("gate_low_rank_sel"),
        py::arg("up_low_rank_sel"),
        py::arg("gate_lora_B"),
        py::arg("up_lora_B"),
        py::arg("gate_up_weight_cpu"),
        py::arg("selected_offsets"),
        py::arg("selected_experts"),
        py::arg("dS_down_sel"),
        py::arg("down_mask_packed"),
        py::arg("down_dropout_p") = 0.0,
        py::arg("p") = 32,
        py::arg("q") = 8,
        py::arg("bm") = 64,
        py::arg("bk") = 512,
        py::arg("g_work") = 128,
        py::arg("lora_scale") = 1.0,
        py::arg("mode") = "cache_first_window",
        py::arg("return_stats") = true);
}

}  // namespace asym_gemm::qwen3_moe
